### ISSUE TITLE
nightly action seems to push multiple untagged images to GHCR

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.pacta#24]
e.g. https://github.com/RMI-PACTA/workflow.pacta/pkgs/container/workflow.pacta/versions?page=1
@AlexAxthelm

**Comment by AlexAxthelm** [comment]
This is expected behavior. The untagged images are the actual images, while the tagged "image" is the manifest, which wraps the image (images for multi-arch builds).

Currently, the `nightly` tag includes this as its `linux/amd64` option:
```
$ docker pull ghcr.io/rmi-pacta/workflow.pacta:nightly@sha256:a8c61e0298d9cf4d9c3b78b5f1021f7b8ca574aff71c61fc46732265190855b0
```
![Screenshot_2024-02-19_14 58 01](https://github.com/RMI-PACTA/workflow.pacta/assets/2974734/96fee211-a54d-40dc-81c1-4676dfca1a65)

We can see that image does actually exist:
![Screenshot_2024-02-19_14 58 43](https://github.com/RMI-PACTA/workflow.pacta/assets/2974734/52395c82-aa7f-4d6a-a9c6-f49e761537ad)

Related to the manifest description in https://github.com/RMI-PACTA/workflow.pacta/issues/25#issuecomment-1952609421

Closing as expected behavior.
