### ISSUE TITLE
Docker build action pushes "unknown/unknown" arch image

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.pacta#25]
e.g. https://github.com/RMI-PACTA/workflow.pacta/pkgs/container/workflow.pacta/154024817?tag=nightly
@AlexAxthelm

**Comment by AlexAxthelm** [comment]
This appears to be working as expected. 

When `buildx` creates a manifest (which is necessary to allow for multi-arch images), the manifest gets labelled with `unknown/unknown`, since it's not a real image, but a effectively pointer to real images.

> To prevent container runtimes from accidentally pulling or running the image described in the manifest, the platform property of the attestation manifest will be set to `unknown/unknown`

https://docs.docker.com/build/attestations/attestation-storage/#attestation-manifest-descriptor

Closing, as this is working correctly.
